#include "libsed/security/hash_password.h"
#include <cassert>
#include <cstdio>
#include <cstring>

#ifndef TEST
#define TEST(suite, name) void test_##suite##_##name()
#define EXPECT_EQ(a, b) assert((a) == (b))
#define EXPECT_NE(a, b) assert((a) != (b))
#define EXPECT_TRUE(a) assert(a)
#define RUN_TEST(suite, name) do { printf("  " #suite "." #name "..."); test_##suite##_##name(); printf(" OK\n"); } while(0)
#endif

using namespace libsed;

// Byte-wise equality against a 32-byte hex-encoded reference.
// Keeps the test-vector intent readable without pulling in a hex helper.
static bool bytesMatchHex(const Bytes& actual, const char* hex32) {
    if (actual.size() != 32) return false;
    for (int i = 0; i < 32; ++i) {
        unsigned v;
        if (sscanf(hex32 + i*2, "%02x", &v) != 1) return false;
        if (actual[i] != (uint8_t)v) return false;
    }
    return true;
}

// Variable-length hex compare — for SHA-1 (20B), HMAC-SHA1 (20B),
// PBKDF2-SHA1 of arbitrary dkLen.
static bool bytesMatchHexN(const Bytes& actual, const char* hex, size_t expectLen) {
    if (actual.size() != expectLen) return false;
    for (size_t i = 0; i < expectLen; ++i) {
        unsigned v;
        if (sscanf(hex + i*2, "%02x", &v) != 1) return false;
        if (actual[i] != (uint8_t)v) return false;
    }
    return true;
}

// ── SHA-256 vectors (NIST FIPS 180-2) ──────────────────────────────

TEST(Hash, Sha256Empty) {
    auto h = HashPassword::sha256(nullptr, 0);
    EXPECT_TRUE(bytesMatchHex(h,
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"));
}

TEST(Hash, Sha256Abc) {
    std::string msg = "abc";
    auto h = HashPassword::sha256(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHex(h,
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
}

TEST(Hash, Sha256LongString) {
    std::string msg =
        "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";
    auto h = HashPassword::sha256(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHex(h,
        "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"));
}

// ── HMAC-SHA-256 (RFC 4231 Test Case 1) ────────────────────────────

TEST(Hash, HmacSha256_Rfc4231_Case1) {
    Bytes key(20, 0x0b);
    std::string msg = "Hi There";
    Bytes data(msg.begin(), msg.end());
    auto mac = HashPassword::hmacSha256(key, data);
    EXPECT_TRUE(bytesMatchHex(mac,
        "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"));
}

// ── PBKDF2-HMAC-SHA-256 (RFC 7914 style, 32-byte output) ───────────
// Reference vectors generated by OpenSSL PKCS5_PBKDF2_HMAC with SHA-256.

TEST(Hash, Pbkdf2Sha256_1Iteration) {
    auto dk = HashPassword::pbkdf2Sha256("password", Bytes{'s','a','l','t'}, 1, 32);
    EXPECT_TRUE(bytesMatchHex(dk,
        "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b"));
}

TEST(Hash, Pbkdf2Sha256_4096Iterations) {
    auto dk = HashPassword::pbkdf2Sha256("password", Bytes{'s','a','l','t'}, 4096, 32);
    EXPECT_TRUE(bytesMatchHex(dk,
        "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a"));
}

// ── passwordToBytes: SHA-256 of UTF-8 password bytes ───────────────
// libsed uses plain SHA-256(password). The intent is to produce a
// deterministic 32-byte PIN that satisfies drives with MSID-length
// minimums while staying stable across hosts.

TEST(Hash, PasswordToBytes_Sha256OfInput) {
    auto a = HashPassword::passwordToBytes("test");
    EXPECT_TRUE(bytesMatchHex(a,
        "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"));

    // Distinct inputs → distinct outputs (sanity vs trivial collisions).
    auto b = HashPassword::passwordToBytes("Test"); // capital T
    EXPECT_NE(a, b);
}

// ── sedutil parity / divergence ────────────────────────────────────
// sedutil's DtaHashPwd hashes passwords with PBKDF2-HMAC-SHA1 using the
// drive's MSID as salt (75000 iterations, 32-byte output). libsed's
// `passwordToBytes` is plain SHA-256. The two are NOT interoperable
// at the PIN-byte level: a drive that stored its C_PIN via libsed will
// reject sedutil's hash for the same password and vice versa.
//
// These tests pin the libsed SHA-256 path so it does not silently drift
// into PBKDF2 territory, and assert the divergence is real (so future
// "parity" attempts do not accidentally hide it).

TEST(Hash, SedutilDivergence_Sha256VsPbkdf2Sha256) {
    // Even if we ran PBKDF2-HMAC-SHA256 (which is NOT what sedutil does
    // either — sedutil uses SHA-1), the result still differs from the
    // plain SHA-256 that libsed stores. This makes the "libsed PIN !=
    // PBKDF2-derived PIN" property explicit.
    std::string password = "TestSIDPassword123";
    Bytes salt = {'M','S','I','D'};

    auto libsedPin = HashPassword::passwordToBytes(password);
    auto pbkdf2Pin = HashPassword::pbkdf2Sha256(password, salt, 75000, 32);

    EXPECT_EQ(libsedPin.size(), 32u);
    EXPECT_EQ(pbkdf2Pin.size(), 32u);
    EXPECT_NE(libsedPin, pbkdf2Pin); // NOT interoperable
}

TEST(Hash, PasswordToBytes_StableForSamePassword) {
    // Determinism: two calls with the same password yield identical PINs.
    // If this ever flips to a salted/iterated scheme, this test fails and
    // forces the author to update passwordToBytes' contract explicitly.
    auto a = HashPassword::passwordToBytes("TestSIDPassword123");
    auto b = HashPassword::passwordToBytes("TestSIDPassword123");
    EXPECT_EQ(a, b);
}

// ── SHA-1 vectors (FIPS 180-4 / RFC 3174) ──────────────────────────

TEST(Hash, Sha1Empty) {
    auto h = HashPassword::sha1(nullptr, 0);
    EXPECT_TRUE(bytesMatchHexN(h,
        "da39a3ee5e6b4b0d3255bfef95601890afd80709", 20));
}

TEST(Hash, Sha1Abc) {
    std::string msg = "abc";
    auto h = HashPassword::sha1(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHexN(h,
        "a9993e364706816aba3e25717850c26c9cd0d89d", 20));
}

TEST(Hash, Sha1LongString) {
    // FIPS 180-4 §A.2 — 56-byte test vector
    std::string msg = "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";
    auto h = HashPassword::sha1(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHexN(h,
        "84983e441c3bd26ebaae4aa1f95129e5e54670f1", 20));
}

// ── HMAC-SHA-1 vectors (RFC 2202) ──────────────────────────────────

TEST(Hash, HmacSha1_Rfc2202_Case1) {
    // key = 20 bytes 0x0b, data = "Hi There"
    Bytes key(20, 0x0b);
    std::string data = "Hi There";
    Bytes msg(data.begin(), data.end());
    auto mac = HashPassword::hmacSha1(key, msg);
    EXPECT_TRUE(bytesMatchHexN(mac,
        "b617318655057264e28bc0b6fb378c8ef146be00", 20));
}

TEST(Hash, HmacSha1_Rfc2202_Case2) {
    // key = "Jefe", data = "what do ya want for nothing?"
    std::string keyStr = "Jefe";
    Bytes key(keyStr.begin(), keyStr.end());
    std::string data = "what do ya want for nothing?";
    Bytes msg(data.begin(), data.end());
    auto mac = HashPassword::hmacSha1(key, msg);
    EXPECT_TRUE(bytesMatchHexN(mac,
        "effcdf6ae5eb2fa2d27416d5f184df9c259a7c79", 20));
}

// ── PBKDF2-HMAC-SHA1 vectors (RFC 6070) ────────────────────────────

TEST(Hash, Pbkdf2Sha1_Rfc6070_Case1) {
    Bytes salt = {'s','a','l','t'};
    auto dk = HashPassword::pbkdf2Sha1("password", salt, /*iter*/1, /*dkLen*/20);
    EXPECT_TRUE(bytesMatchHexN(dk,
        "0c60c80f961f0e71f3a9b524af6012062fe037a6", 20));
}

TEST(Hash, Pbkdf2Sha1_Rfc6070_Case2) {
    Bytes salt = {'s','a','l','t'};
    auto dk = HashPassword::pbkdf2Sha1("password", salt, /*iter*/2, /*dkLen*/20);
    EXPECT_TRUE(bytesMatchHexN(dk,
        "ea6c014dc72d6f8ccd1ed92ace1d41f0d8de8957", 20));
}

TEST(Hash, Pbkdf2Sha1_Rfc6070_Case3) {
    Bytes salt = {'s','a','l','t'};
    auto dk = HashPassword::pbkdf2Sha1("password", salt, /*iter*/4096, /*dkLen*/20);
    EXPECT_TRUE(bytesMatchHexN(dk,
        "4b007901b765489abead49d926f721d065a429c1", 20));
}

TEST(Hash, Pbkdf2Sha1_Rfc6070_Case5_LongerOutput) {
    // dkLen=25 forces 2 PBKDF2 blocks (20 + 5 bytes from 2nd block).
    // Verifies the multi-block accumulation logic.
    Bytes salt;
    std::string saltStr = "saltSALTsaltSALTsaltSALTsaltSALTsalt";
    salt.assign(saltStr.begin(), saltStr.end());
    auto dk = HashPassword::pbkdf2Sha1("passwordPASSWORDpassword",
                                         salt, /*iter*/4096, /*dkLen*/25);
    EXPECT_TRUE(bytesMatchHexN(dk,
        "3d2eec4fe41c849b80c8d83662c0e44a8b291a964cf2f07038", 25));
}

// ── sedutilHash() — sedutil-cli (DTA fork) compatibility ──────────

TEST(Hash, SedutilHash_DelegatesToPbkdf2Sha1) {
    // sedutilHash 는 pbkdf2Sha1 의 wrapper. RFC 6070 Case 3 인자로 호출
    // 했을 때 같은 결과가 나오는지 확인 (default iter/keyLen 무시하고
    // 명시 인자 사용).
    Bytes salt = {'s','a','l','t'};
    auto dk = HashPassword::sedutilHash("password", salt,
                                          /*iter*/4096, /*keyLen*/20);
    EXPECT_TRUE(bytesMatchHexN(dk,
        "4b007901b765489abead49d926f721d065a429c1", 20));
}

TEST(Hash, SedutilHash_Default_75000_32B) {
    // sedutil DTA fork 의 실제 사용 형태 (iter=75000, keyLen=32) 은
    // 단위 테스트 내에서 OpenSSL 등 외부 reference 없이 검증 곤란하므로
    // 여기선 (a) 길이가 정확히 32B, (b) 같은 입력에 대해 결정론적,
    // (c) 작은 변경에 민감 (확산성) 만 확인. 실제 wire-level byte-
    // identical 검증은 hardware capture (golden_validator) 로 수행.
    Bytes serial(20, 0x41); // 20 bytes 'A'
    auto a = HashPassword::sedutilHash("password", serial);
    auto b = HashPassword::sedutilHash("password", serial);
    auto c = HashPassword::sedutilHash("Password", serial);  // P 대문자
    EXPECT_EQ(a.size(), 32u);
    EXPECT_EQ(a, b);
    EXPECT_NE(a, c);
}

#ifndef GTEST_INCLUDE_GTEST_GTEST_H_
void run_hash_tests() {
    printf("Hash tests:\n");
    RUN_TEST(Hash, Sha256Empty);
    RUN_TEST(Hash, Sha256Abc);
    RUN_TEST(Hash, Sha256LongString);
    RUN_TEST(Hash, HmacSha256_Rfc4231_Case1);
    RUN_TEST(Hash, Pbkdf2Sha256_1Iteration);
    RUN_TEST(Hash, Pbkdf2Sha256_4096Iterations);
    RUN_TEST(Hash, PasswordToBytes_Sha256OfInput);
    RUN_TEST(Hash, SedutilDivergence_Sha256VsPbkdf2Sha256);
    RUN_TEST(Hash, PasswordToBytes_StableForSamePassword);
    RUN_TEST(Hash, Sha1Empty);
    RUN_TEST(Hash, Sha1Abc);
    RUN_TEST(Hash, Sha1LongString);
    RUN_TEST(Hash, HmacSha1_Rfc2202_Case1);
    RUN_TEST(Hash, HmacSha1_Rfc2202_Case2);
    RUN_TEST(Hash, Pbkdf2Sha1_Rfc6070_Case1);
    RUN_TEST(Hash, Pbkdf2Sha1_Rfc6070_Case2);
    RUN_TEST(Hash, Pbkdf2Sha1_Rfc6070_Case3);
    RUN_TEST(Hash, Pbkdf2Sha1_Rfc6070_Case5_LongerOutput);
    RUN_TEST(Hash, SedutilHash_DelegatesToPbkdf2Sha1);
    RUN_TEST(Hash, SedutilHash_Default_75000_32B);
    printf("  All Hash tests passed!\n\n");
}
#endif
