#include "libsed/security/hash_password.h"
#include <cassert>
#include <cstdio>
#include <cstring>

#ifndef TEST
#define TEST(suite, name) void test_##suite##_##name()
#define EXPECT_EQ(a, b) assert((a) == (b))
#define EXPECT_NE(a, b) assert((a) != (b))
#define EXPECT_TRUE(a) assert(a)
#define RUN_TEST(suite, name) do { printf("  " #suite "." #name "..."); test_##suite##_##name(); printf(" OK\n"); } while(0)
#endif

using namespace libsed;

// Byte-wise equality against a 32-byte hex-encoded reference.
// Keeps the test-vector intent readable without pulling in a hex helper.
static bool bytesMatchHex(const Bytes& actual, const char* hex32) {
    if (actual.size() != 32) return false;
    for (int i = 0; i < 32; ++i) {
        unsigned v;
        if (sscanf(hex32 + i*2, "%02x", &v) != 1) return false;
        if (actual[i] != (uint8_t)v) return false;
    }
    return true;
}

// ── SHA-256 vectors (NIST FIPS 180-2) ──────────────────────────────

TEST(Hash, Sha256Empty) {
    auto h = HashPassword::sha256(nullptr, 0);
    EXPECT_TRUE(bytesMatchHex(h,
        "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"));
}

TEST(Hash, Sha256Abc) {
    std::string msg = "abc";
    auto h = HashPassword::sha256(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHex(h,
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad"));
}

TEST(Hash, Sha256LongString) {
    std::string msg =
        "abcdbcdecdefdefgefghfghighijhijkijkljklmklmnlmnomnopnopq";
    auto h = HashPassword::sha256(reinterpret_cast<const uint8_t*>(msg.data()), msg.size());
    EXPECT_TRUE(bytesMatchHex(h,
        "248d6a61d20638b8e5c026930c3e6039a33ce45964ff2167f6ecedd419db06c1"));
}

// ── HMAC-SHA-256 (RFC 4231 Test Case 1) ────────────────────────────

TEST(Hash, HmacSha256_Rfc4231_Case1) {
    Bytes key(20, 0x0b);
    std::string msg = "Hi There";
    Bytes data(msg.begin(), msg.end());
    auto mac = HashPassword::hmacSha256(key, data);
    EXPECT_TRUE(bytesMatchHex(mac,
        "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7"));
}

// ── PBKDF2-HMAC-SHA-256 (RFC 7914 style, 32-byte output) ───────────
// Reference vectors generated by OpenSSL PKCS5_PBKDF2_HMAC with SHA-256.

TEST(Hash, Pbkdf2Sha256_1Iteration) {
    auto dk = HashPassword::pbkdf2Sha256("password", Bytes{'s','a','l','t'}, 1, 32);
    EXPECT_TRUE(bytesMatchHex(dk,
        "120fb6cffcf8b32c43e7225256c4f837a86548c92ccc35480805987cb70be17b"));
}

TEST(Hash, Pbkdf2Sha256_4096Iterations) {
    auto dk = HashPassword::pbkdf2Sha256("password", Bytes{'s','a','l','t'}, 4096, 32);
    EXPECT_TRUE(bytesMatchHex(dk,
        "c5e478d59288c841aa530db6845c4c8d962893a001ce4e11a4963873aa98134a"));
}

// ── passwordToBytes: SHA-256 of UTF-8 password bytes ───────────────
// libsed uses plain SHA-256(password). The intent is to produce a
// deterministic 32-byte PIN that satisfies drives with MSID-length
// minimums while staying stable across hosts.

TEST(Hash, PasswordToBytes_Sha256OfInput) {
    auto a = HashPassword::passwordToBytes("test");
    EXPECT_TRUE(bytesMatchHex(a,
        "9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08"));

    // Distinct inputs → distinct outputs (sanity vs trivial collisions).
    auto b = HashPassword::passwordToBytes("Test"); // capital T
    EXPECT_NE(a, b);
}

// ── sedutil parity / divergence ────────────────────────────────────
// sedutil's DtaHashPwd hashes passwords with PBKDF2-HMAC-SHA1 using the
// drive's MSID as salt (75000 iterations, 32-byte output). libsed's
// `passwordToBytes` is plain SHA-256. The two are NOT interoperable
// at the PIN-byte level: a drive that stored its C_PIN via libsed will
// reject sedutil's hash for the same password and vice versa.
//
// These tests pin the libsed SHA-256 path so it does not silently drift
// into PBKDF2 territory, and assert the divergence is real (so future
// "parity" attempts do not accidentally hide it).

TEST(Hash, SedutilDivergence_Sha256VsPbkdf2Sha256) {
    // Even if we ran PBKDF2-HMAC-SHA256 (which is NOT what sedutil does
    // either — sedutil uses SHA-1), the result still differs from the
    // plain SHA-256 that libsed stores. This makes the "libsed PIN !=
    // PBKDF2-derived PIN" property explicit.
    std::string password = "TestSIDPassword123";
    Bytes salt = {'M','S','I','D'};

    auto libsedPin = HashPassword::passwordToBytes(password);
    auto pbkdf2Pin = HashPassword::pbkdf2Sha256(password, salt, 75000, 32);

    EXPECT_EQ(libsedPin.size(), 32u);
    EXPECT_EQ(pbkdf2Pin.size(), 32u);
    EXPECT_NE(libsedPin, pbkdf2Pin); // NOT interoperable
}

TEST(Hash, PasswordToBytes_StableForSamePassword) {
    // Determinism: two calls with the same password yield identical PINs.
    // If this ever flips to a salted/iterated scheme, this test fails and
    // forces the author to update passwordToBytes' contract explicitly.
    auto a = HashPassword::passwordToBytes("TestSIDPassword123");
    auto b = HashPassword::passwordToBytes("TestSIDPassword123");
    EXPECT_EQ(a, b);
}

#ifndef GTEST_INCLUDE_GTEST_GTEST_H_
void run_hash_tests() {
    printf("Hash tests:\n");
    RUN_TEST(Hash, Sha256Empty);
    RUN_TEST(Hash, Sha256Abc);
    RUN_TEST(Hash, Sha256LongString);
    RUN_TEST(Hash, HmacSha256_Rfc4231_Case1);
    RUN_TEST(Hash, Pbkdf2Sha256_1Iteration);
    RUN_TEST(Hash, Pbkdf2Sha256_4096Iterations);
    RUN_TEST(Hash, PasswordToBytes_Sha256OfInput);
    RUN_TEST(Hash, SedutilDivergence_Sha256VsPbkdf2Sha256);
    RUN_TEST(Hash, PasswordToBytes_StableForSamePassword);
    printf("  All Hash tests passed!\n\n");
}
#endif
